guacd-hostname: 127.0.0.1
guacd-port: 4822

mysql-hostname: localhost
mysql-port: 3306
mysql-database: guacamole_db
mysql-username: guacadmin
mysql-password: __TURNKEY_GUACAMOLE_DATABASE_PASSWORD__

mysql-auto-create-accounts: false

extension-priority: mysql
