#!/bin/bash -e

GUAC_VERSION="1.6.0"
DOWNLOAD_BASE="https://downloads.apache.org/guacamole/${GUAC_VERSION}"
BUILD_DIR="/usr/src/guacamole-build"
GUAC_HOME="/etc/guacamole"
TOMCAT_WEBAPPS="/var/lib/tomcat10/webapps"
GUAC_DOWNLOADS="
source/guacamole-server-${GUAC_VERSION}.tar.gz
binary/guacamole-${GUAC_VERSION}.war
binary/guacamole-auth-jdbc-${GUAC_VERSION}.tar.gz
binary/guacamole-auth-ldap-${GUAC_VERSION}.tar.gz
binary/guacamole-auth-sso-${GUAC_VERSION}.tar.gz
"

mkdir -p "${BUILD_DIR}"
mkdir -p "${GUAC_HOME}/extensions"
mkdir -p "${GUAC_HOME}/lib"

cd "${BUILD_DIR}"

for p in ${GUAC_DOWNLOADS}; do
    curl -fL "${DOWNLOAD_BASE}/${p}" -o $(basename "${p}")
done

sha256sum --check - <<EOF
8bc45675da96d7b6f39728160181e3d4ff3c08f460f6d26de5805b642bf13f2b  guacamole-server-1.6.0.tar.gz
b41ceb1e2df010b54db563e0b00edb8d5fe9f073c6168462e4c978df0fc6e716  guacamole-1.6.0.war
b07f27adc370324108527b6929f61d93880026d57c1033064bd1c55b881c7497  guacamole-auth-ldap-1.6.0.tar.gz
97bc5fd3d67d25c0e98a475d1dfd308a037859f549fac47171c723b7a7039366  guacamole-auth-jdbc-1.6.0.tar.gz
e957984471ac50a87f472f51aec9bf7e378ae67ce2502ff938030011a670dcae  guacamole-auth-sso-1.6.0.tar.gz
EOF

tar -xzf "guacamole-server-${GUAC_VERSION}.tar.gz"
tar -xzf "guacamole-auth-jdbc-${GUAC_VERSION}.tar.gz"

cd "guacamole-server-${GUAC_VERSION}"

./configure \
    --with-systemd-dir=/lib/systemd/system \
    --disable-static

make -j"$(nproc)"
make install
ldconfig

cd "${BUILD_DIR}"

jakartaee-migration \
    "guacamole-${GUAC_VERSION}.war" \
    "${TOMCAT_WEBAPPS}/guacamole.war"

MYSQL_EXTENSION="$(
    find \
        "guacamole-auth-jdbc-${GUAC_VERSION}" \
        -type f \
        -name "guacamole-auth-jdbc-mysql-${GUAC_VERSION}.jar" \
        -print \
        -quit
)"

test -n "${MYSQL_EXTENSION}"

jakartaee-migration \
    "${MYSQL_EXTENSION}" \
    "${GUAC_HOME}/extensions/guacamole-auth-jdbc-mysql-${GUAC_VERSION}.jar"

MYSQL_SCHEMA_DIR="$(
    find \
        "guacamole-auth-jdbc-${GUAC_VERSION}" \
        -type d \
        -path "*/mysql/schema" \
        -print \
        -quit
)"

test -n "${MYSQL_SCHEMA_DIR}"

MARIADB_JAR="$(
    find /usr/share/java \
        -maxdepth 1 \
        -type f \
        -name "mariadb-java-client*.jar" \
        -print \
        -quit
)"

test -n "${MARIADB_JAR}"
ln -sf "${MARIADB_JAR}" "${GUAC_HOME}/lib/mariadb-java-client.jar"

LDAP_EXTENSION="$(
    find \
        "guacamole-auth-ldap-${GUAC_VERSION}" \
        -type f \
        -name "guacamole-auth-ldap-${GUAC_VERSION}.jar" \
        -print \
        -quit
)"

test -n "${LDAP_EXTENSION}"

jakartaee-migration \
    "${LDAP_EXTENSION}" \
    "${GUAC_HOME}/extensions/guacamole-auth-ldap-${GUAC_VERSION}.jar"

SSO_EXTENSION="$(
    find \
        "guacamole-auth-sso-${GUAC_VERSION}" \
        -type f \
        -name "guacamole-auth-sso-${GUAC_VERSION}.jar" \
        -print \
        -quit
)"

test -n "${SSO_EXTENSION}"

jakartaee-migration \
    "${SSO_EXTENSION}" \
    "${GUAC_HOME}/extensions/guacamole-auth-sso-${GUAC_VERSION}.jar"


install -d -o guacd -g guacd -m 0750 /var/lib/guacd
install -d -m 0750 /usr/share/guacamole/mysql-schema
install -m 0644 "${MYSQL_SCHEMA_DIR}"/*.sql /usr/share/guacamole/mysql-schema

systemctl enable guacd.service

rm -rf "${BUILD_DIR}"
