#!/bin/bash -e

source /usr/local/src/env.sh

GUAC_HOME="/etc/guacamole"
DOWNLOAD_BASE="https://downloads.apache.org/guacamole/${GUAC_VERSION}"
DOWNLOAD_PROXY="${FAB_HTTP_PROXY:+--proxy ${FAB_HTTP_PROXY}}"
GUAC_DOWNLOADS="
source/guacamole-server-${GUAC_VERSION}.tar.gz
binary/guacamole-${GUAC_VERSION}.war
binary/guacamole-auth-jdbc-${GUAC_VERSION}.tar.gz
binary/guacamole-auth-ldap-${GUAC_VERSION}.tar.gz
binary/guacamole-auth-sso-${GUAC_VERSION}.tar.gz
binary/guacamole-history-recording-storage-${GUAC_VERSION}.tar.gz
"
TOMCAT_WEBAPPS="/var/lib/tomcat10/webapps"

mkdir -p "${BUILD_DIR}"
mkdir -p "${GUAC_HOME}/extensions"
mkdir -p "${GUAC_HOME}/lib"

cd "${BUILD_DIR}"

for p in ${GUAC_DOWNLOADS}; do
    curl -fLO ${DOWNLOAD_PROXY} "${DOWNLOAD_BASE}/${p}"
done

sha256sum --check - <<EOF
8bc45675da96d7b6f39728160181e3d4ff3c08f460f6d26de5805b642bf13f2b  guacamole-server-1.6.0.tar.gz
b41ceb1e2df010b54db563e0b00edb8d5fe9f073c6168462e4c978df0fc6e716  guacamole-1.6.0.war
b07f27adc370324108527b6929f61d93880026d57c1033064bd1c55b881c7497  guacamole-auth-ldap-1.6.0.tar.gz
97bc5fd3d67d25c0e98a475d1dfd308a037859f549fac47171c723b7a7039366  guacamole-auth-jdbc-1.6.0.tar.gz
e957984471ac50a87f472f51aec9bf7e378ae67ce2502ff938030011a670dcae  guacamole-auth-sso-1.6.0.tar.gz
823ea44766035cf8a8b108946547c94749022b7010c9961ffd3e73fd5659796d  guacamole-history-recording-storage-1.6.0.tar.gz
EOF

for p in ${GUAC_DOWNLOADS}; do
    local archive = $(basename "${p}")
    if [ ${archive: -7} == '.tar.gz' ]; then
	local target = "${archive%%.tar.gz}"
	tar -xzf "${archive}"
	if [ x$(dirname "${p}") == "xsource" ]; then
	    cd "${target}"
	   
	    ./configure --with-systemd-dir=/lib/systemd/system --disable-static

	    make -j"$(nproc)"
	    make install
	    ldconfig

	    cd -
        else
	    case "${target}" in
		*jdbc*) local jar="${target/jdbc/jdbc-mysql}.jar";;
		*sso*)  local jar="${target/sso/sso-openid}.jar";;
		*)      local jar="${target}.jar";;
	    esac

	    local extension=$(find "${target}" -type f -name "${jar}" -print -quit)

	    test -n "${extension}"
	    javax2jakarta "${extension}" "${GUAC_VERSION}/extensions/${extension}"
	fi
    else
	javax2jakarta "${target}" "${TOMCAT_WEBAPPS}/${target/-${GUAC_VERSION}}"
    fi
done

MARIADB_JAR="$(
    find /usr/share/java \
        -maxdepth 1 \
        -type f \
        -name "mariadb-java-client*.jar" \
        -print \
        -quit
)"

test -n "${MARIADB_JAR}"
ln -sf "${MARIADB_JAR}" "${GUAC_HOME}/lib/mariadb-java-client.jar"

install -d -o guacd -g guacd -m 0751 /var/lib/guacd
install -d -o guacd -g tomcat -m 2750 /var/lib/guacd/recordings

systemctl enable guacd.service

