#!/bin/bash -e

DB_NAME="guacamole_db"
DB_USER="guacadmin"
DB_PASS=$(mcookie)

MYSQL_SCHEMA_DIR="$(
    find \
        "${FAB_BUILD_DIR}/guacamole-auth-jdbc-${FAB_GUAC_VERSION}" \
        -type d \
        -path "*/mysql/schema" \
        -print \
        -quit
)"

test -n "${MYSQL_SCHEMA_DIR}"

# create database
systemctl start mysql
mysqladmin create "${DB_NAME}"
cat "${MYSQL_SCHEMA_DIR}"/*.sql | mysql --batch

# Create database user for Guacamole
mysql <<EOF
CREATE USER 'guacadmin' IDENTIFIED BY '${DB_PASS}';
GRANT SELECT,INSERT,UPDATE,DELETE ON guacamole_db.* TO 'guacadmin';
FLUSH PRIVILEGES;
EOF

systemctl stop mysql

