#!/bin/sh -e
# Purge unneeded packages
PURGELIST="
build-essential
ca-certificates
curl
freerdp2-dev
libavcodec-dev
libavformat-dev
libavutil-dev
libcairo2-dev
libjpeg62-turbo-dev
libossp-uuid-dev
libpango1.0-dev
libpng-dev
libpulse-dev
libssh2-1-dev
libssl-dev
libswscale-dev
libtcnative-1
libtelnet-dev
libtool-bin
libvncserver-dev
libvorbis-dev
libwebp-dev
libwebsockets-dev
pkg-config
tomcat-jakartaee-migration
uuid-dev
"

apt-get purge -y ${PURGELIST} || true
apt autoremove --purge || true
ldconfig
