#!/bin/bash -e
# regenerate guacamole secret key and mysql password

. /etc/default/inithooks

CONF="/etc/guacamole/guacamole.properties"
PASSWORD=$(mcookie)

update_conf() {
    sed -i "/$1/$2/" $CONF
}

update_conf 'public $secret' "'$(mcookie)'"

update_conf '__TURNKEY_GUACAMOLE_DATABASE_PASSWORD__' "'$PASSWORD'"
$INITHOOKS_PATH/bin/mysqlconf.py --user=guacadmin --pass="$PASSWORD"
systemctl restart guacd
